# Generated by Django 5.2.6 on 2025-12-18 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0003_alter_layer_name_and_more'),
        ('sublayers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sublayer',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name='sublayer',
            constraint=models.UniqueConstraint(fields=('name', 'layer'), name='unique_sublayer_name_per_layer'),
        ),
    ]
