# Generated by Django 5.2.6 on 2025-12-17 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('layers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer',
            name='inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layers', to='inventory.inventory'),
        ),
    ]
