# Generated by Django 5.2.6 on 2025-12-18 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('layers', '0002_alter_layer_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name='layer',
            constraint=models.UniqueConstraint(fields=('name', 'inventory'), name='unique_layer_name_per_inventory'),
        ),
    ]
