# Generated by Django 5.2.6 on 2026-01-12 21:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0003_alter_layer_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='user',
            field=models.ForeignKey(default='94bc416c-5804-4a93-9b1d-29bcec82d991', on_delete=django.db.models.deletion.CASCADE, related_name='layers', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
