# Generated by Django 5.2.6 on 2026-05-18 08:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0006_alter_company_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryZone',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('reference', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('city', models.CharField(help_text='Target city or regional hub name (e.g. Nairobi, Mombasa, Kisumu)', max_length=150)),
                ('fee', models.DecimalField(decimal_places=2, default=0.0, help_text='Shipping fee for delivery to this zone', max_digits=10)),
                ('estimated_days', models.PositiveIntegerField(default=2, help_text='Estimated time in days for delivery to arrive')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this delivery zone is currently active')),
                ('company', models.ForeignKey(help_text='Supplier company that offers delivery to this zone', on_delete=django.db.models.deletion.CASCADE, related_name='delivery_zones', to='companies.company')),
            ],
            options={
                'verbose_name': 'Delivery Zone',
                'verbose_name_plural': 'Delivery Zones',
                'ordering': ['city', '-created_at'],
                'unique_together': {('company', 'city')},
            },
        ),
    ]
