# Generated by Django 5.2.6 on 2026-05-18 08:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('delivery', '0001_initial'),
        ('orders', '0003_order_carrier_details_order_delivery_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDelivery',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('reference', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('delivery_method', models.CharField(choices=[('DELIVERY', 'Supplier Managed Delivery'), ('PICKUP', 'Contractor Self-Pickup')], default='DELIVERY', max_length=30)),
                ('shipping_fee', models.DecimalField(decimal_places=2, default=0.0, help_text='Calculated shipping fee captured at checkout', max_digits=10)),
                ('delivery_address', models.TextField(blank=True, help_text='Detailed location for delivery or pickup instructions', null=True)),
                ('recipient_name', models.CharField(blank=True, help_text='Designated contact person name for delivery/pickup', max_length=200, null=True)),
                ('recipient_phone', models.CharField(blank=True, help_text='Designated contact person phone number', max_length=30, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Dispatch'), ('DISPATCHED', 'In Transit'), ('READY_FOR_PICKUP', 'Ready for Pickup'), ('COMPLETED', 'Fulfilled'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=50)),
                ('secure_pin', models.CharField(blank=True, help_text='Generated secure 6-digit PIN code to verify receipt', max_length=20, null=True)),
                ('carrier_name', models.CharField(blank=True, help_text='Name of the carrier or driver delivering the materials', max_length=255, null=True)),
                ('tracking_number', models.CharField(blank=True, help_text='Tracking reference for carrier', max_length=100, null=True)),
                ('delivery_zone', models.ForeignKey(blank=True, help_text='Selected delivery zone (if delivery method is supplier delivery)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='delivery.deliveryzone')),
                ('order', models.OneToOneField(help_text='The supplier split order associated with this delivery detail', on_delete=django.db.models.deletion.CASCADE, related_name='delivery_detail', to='orders.order')),
            ],
            options={
                'verbose_name': 'Order Delivery',
                'verbose_name_plural': 'Order Deliveries',
                'ordering': ['-created_at'],
            },
        ),
    ]
