# Generated by Django 5.2.6 on 2025-12-18 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brackets', '0001_initial'),
        ('sublayeritems', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bracket',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name='bracket',
            constraint=models.UniqueConstraint(fields=('name', 'sublayeritem'), name='unique_bracket_name_per_sublayeritem'),
        ),
    ]
