# Generated by Django 5.2.6 on 2026-01-20 20:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentOption',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('reference', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('payment_type', models.CharField(choices=[('FIXED', 'FIXED'), ('PAYMENT_ON_DELIVERY', 'PAYMENT_ON_DELIVERY'), ('SPLIT_50_50', 'SPLIT_50_50'), ('FLEXIBLE', 'FLEXIBLE')], help_text='Type of payment plan', max_length=50)),
                ('min_deposit_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Required deposit percentage (e.g., 20.00 for 20%), mainly for Flexible', max_digits=5)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_options', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment Option',
                'verbose_name_plural': 'Payment Options',
                'ordering': ['-created_at'],
            },
        ),
    ]
