# Generated by Django 5.2.6 on 2026-02-06 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentoptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentoption',
            name='min_deposit_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Required deposit percentage (e.g., 20.00 for 20%), mainly for Flexible', max_digits=5, null=True),
        ),
    ]
