# Generated by Django 5.2.6 on 2026-02-10 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentoptions', '0002_alter_paymentoption_min_deposit_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentoption',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Annual Interest Rate % (e.g. 10.00 for 10%), only for Flexible', max_digits=5),
        ),
    ]
