# Generated by Django 5.2.6 on 2026-02-06 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartitems', '0001_initial'),
        ('paymentoptions', '0002_alter_paymentoption_min_deposit_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='deposit_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='User input for Flexible deposit', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='duration_months',
            field=models.IntegerField(blank=True, help_text='User input for Flexible duration', null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='payment_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='paymentoptions.paymentoption'),
        ),
    ]
