# Generated by Django 5.2.6 on 2026-02-10 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartitems', '0002_cartitem_deposit_amount_cartitem_duration_months_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='monthly_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='User input for Flexible monthly amount (alternative to duration)', max_digits=10, null=True),
        ),
    ]
