# Generated by Django 5.2.6 on 2026-02-10 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartitems', '0003_cartitem_monthly_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'ordering': ['-created_at']},
        ),
    ]
