# Generated by Django 5.2.6 on 2026-02-10 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartitems', '0004_alter_cartitem_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'ordering': ['-created_at'], 'verbose_name': 'Cart Item', 'verbose_name_plural': 'Cart Items'},
        ),
    ]
