# Generated by Django 5.2.6 on 2026-01-23 08:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paymentoptions', '0001_initial'),
        ('products', '0003_product_price_product_quantity_product_unit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentPlan',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('reference', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plan', models.JSONField(blank=True, null=True)),
                ('payment_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paymentoptions.paymentoption')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_plan', to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_plan', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment Plan',
                'verbose_name_plural': 'Payment Plans',
                'ordering': ('-created_at',),
            },
        ),
    ]
