# Generated by Django 5.2.6 on 2025-09-11 21:27

import accounts.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default=accounts.utils.generate_username, max_length=255, unique=True),
        ),
    ]
