# Generated by Django 5.2.6 on 2025-09-11 22:17

import accounts.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default=accounts.utils.generate_username, editable=False, max_length=255, unique=True),
        ),
    ]
