# Generated by Django 5.2.6 on 2025-10-03 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_is_subcontractor'),
        ('branches', '0002_rename_owner_branch_user'),
        ('sites', '0002_rename_owner_site_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_staff', to='branches.branch'),
        ),
        migrations.AddField(
            model_name='user',
            name='assigned_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_staff', to='sites.site'),
        ),
    ]
