# Generated by Django 5.2.6 on 2025-10-04 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_assigned_branch_user_assigned_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_type',
            field=models.CharField(default='user', editable=False, max_length=20),
        ),
    ]
