# Generated by Django 5.2.6 on 2026-01-23 08:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('paymentplans', '0001_initial'),
        ('products', '0004_product_payment_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('reference', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('price_at_purchase', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('AWAITING_DELIVERY', 'AWAITING_DELIVERY'), ('DISPATCHED', 'DISPATCHED'), ('DELIVERED', 'DELIVERED')], default='PENDING', max_length=50)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('payment_plan', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='order_item', to='paymentplans.paymentplan')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='products.product')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
                'ordering': ['-created_at'],
            },
        ),
    ]
