# Generated by Django 5.2.6 on 2025-12-17 18:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0006_alter_company_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('reference', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('name', models.CharField(help_text='Unique name in the company', max_length=800)),
                ('inventory_code', models.CharField(blank=True, help_text='Unique code for the inventory', max_length=1000, null=True, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the inventory', null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='companies.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_inventories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inventory',
                'verbose_name_plural': 'Inventories',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('company', 'name'), name='unique_inventory_name_per_company')],
            },
        ),
    ]
