# Generated by Django 5.2.6 on 2025-10-04 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employment',
            name='identity',
            field=models.CharField(blank=True, max_length=1000, null=True, unique=True),
        ),
    ]
