# Generated by Django 5.2.6 on 2025-09-11 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='identity',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='company',
            name='type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
