# Generated by Django 5.2.6 on 2025-09-24 21:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_alter_company_user'),
        ('employment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='staff',
            field=models.ManyToManyField(blank=True, related_name='employees', through='employment.Employment', to=settings.AUTH_USER_MODEL),
        ),
    ]
