# Generated by Django 5.2.6 on 2025-10-03 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_company_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=2550, unique=True),
        ),
    ]
