# Generated by Django 5.2.6 on 2025-10-03 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['company', '-created_at'], 'verbose_name': 'Role', 'verbose_name_plural': 'Roles'},
        ),
        migrations.RenameField(
            model_name='role',
            old_name='created_by',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=2555),
        ),
    ]
