# Generated by Django 5.2.6 on 2025-12-12 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0001_initial'),
        ('roles', '0002_alter_role_options_rename_created_by_role_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(blank=True, null=True, related_name='roles_permissions', to='permissions.permission'),
        ),
    ]
