# Generated by Django 5.2.6 on 2025-12-17 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0001_initial'),
        ('roles', '0003_role_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='roles_permissions', to='permissions.permission'),
        ),
    ]
