# Generated by Django 5.2.6 on 2025-10-03 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='owner',
            new_name='user',
        ),
    ]
