# Generated by Django 5.2.6 on 2025-10-04 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_rename_owner_site_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='identity',
            field=models.CharField(blank=True, max_length=700, null=True, unique=True),
        ),
    ]
