# Generated by Django 5.2.6 on 2025-11-08 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0003_alter_site_identity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='name',
            field=models.CharField(default='Kenya', max_length=200),
            preserve_default=False,
        ),
    ]
