# Generated by Django 5.2.6 on 2025-12-18 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sublayeritems', '0001_initial'),
        ('sublayers', '0002_alter_sublayer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sublayeritem',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name='sublayeritem',
            constraint=models.UniqueConstraint(fields=('name', 'sublayer'), name='unique_sublayer_item_name_per_sublayer'),
        ),
    ]
