# Generated by Django 5.2.6 on 2025-12-31 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sublayeritems', '0002_alter_sublayeritem_name_and_more'),
        ('sublayers', '0002_alter_sublayer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sublayeritem',
            name='sublayer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sublayeritems', to='sublayers.sublayer'),
        ),
    ]
