# Generated by Django 5.2.6 on 2026-01-20 19:58

import products.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(default=products.utils.generate_sku, editable=False, max_length=255, unique=True),
        ),
    ]
