# Generated by Django 5.2.6 on 2026-01-23 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentoptions', '0001_initial'),
        ('products', '0003_product_price_product_quantity_product_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='payment_options',
            field=models.ManyToManyField(blank=True, related_name='products', to='paymentoptions.paymentoption'),
        ),
    ]
