# Generated by Django 5.2.6 on 2025-12-03 05:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brackets', '0001_initial'),
        ('branches', '0005_branch_head'),
        ('companies', '0006_alter_company_email'),
        ('layers', '0001_initial'),
        ('sites', '0005_site_head'),
        ('sublayeritems', '0001_initial'),
        ('sublayers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SitesEquipment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('reference', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('source_location', models.CharField(blank=True, max_length=255, null=True)),
                ('product_name', models.CharField(blank=True, max_length=255, null=True)),
                ('specifications', models.JSONField(blank=True, null=True)),
                ('bracket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bracket_sites_equipment', to='brackets.bracket')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_sites_equipment', to='branches.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_sites_equipment', to='companies.company')),
                ('layer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='layer_sites_equipment', to='layers.layer')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_sites_equipment', to='sites.site')),
                ('sublayer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sublayer_sites_equipment', to='sublayers.sublayer')),
                ('sublayeritem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sublayeritem_sites_equipment', to='sublayeritems.sublayeritem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites_equipment', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Site Equipment',
                'verbose_name_plural': 'Site Equipment',
                'ordering': ['-created_at'],
            },
        ),
    ]
