# Generated by Django 5.2.6 on 2025-12-03 06:28

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitesequipment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesequipment',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='site_equipment'),
        ),
    ]
